# Generated by Django 5.1.1 on 2024-09-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_kategoriler_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
