# Generated by Django 5.1.1 on 2024-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_markalar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markalar',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AddField(
            model_name='markalar',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='markalar',
            name='aktifmi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='markalar',
            name='isim',
            field=models.CharField(default='Belirsiz', max_length=255),
        ),
        migrations.AddField(
            model_name='markalar',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='markaresimleri/'),
        ),
        migrations.AddField(
            model_name='markalar',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='markalar',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='markalar',
            name='slug',
            field=models.SlugField(default='Belirsiz', max_length=255, unique=True),
        ),
    ]
