# Generated by Django 5.1.1 on 2024-09-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_remove_kategoriler_ustkatogroi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.kategoriler'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.markalar'),
        ),
    ]
