# Generated by Django 5.1.1 on 2024-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_etiketler_urunler_etiketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='anasayfa',
            field=models.BooleanField(default=False),
        ),
    ]
