# Generated by Django 5.1.1 on 2024-10-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0010_urunler_anasayfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='anasayfa',
            field=models.BooleanField(default=True),
        ),
    ]
