# Generated by Django 5.1.1 on 2024-10-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0012_varyasyonlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='varyasyonlar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.varyasyonlar'),
        ),
    ]
